react-native-sensors/react-native-sensors

README.md
android/src/main/java/com/sensors/Accelerometer.java
android/src/main/java/com/sensors/Gyroscope.java

hi,
My modifications avoid the crash of the module if the user does not have the sensor on his phone.

avoid crash at the init of the module.

---

package.json

Addressing issue https://github.com/react-native-sensors/react-native-sensors/issues/17

Relax react-native version dependency

---

README.md
index.js
src/decorator.js
src/sensors.js

Hello,
Here is a PR to address #24. It removes public reference to the magnetometer feature that is not ready yet. I haven't removed internal references because they will likely be used to implement the rest of the feature.

Remove public mentions of magnetometer WIP feature

---

README.md
src/sensors.js

See https://github.com/react-native-sensors/react-native-sensors/pull/35#issuecomment-336072691

Restore the original api

---

index.js
src/__tests__/sensors.js
src/decorator.js
src/sensors.js

This pull request applies code style fixes from an analysis carried out by [StyleJS](https://stylejs.io).
---
For more information, click [here](https://stylejs.io/analyses/1107).

Apply fixes from StyleJS

---

README.md
android/src/main/java/com/sensors/Accelerometer.java
android/src/main/java/com/sensors/Gyroscope.java
ios/Accelerometer.h
ios/Accelerometer.m
ios/Gyroscope.h
ios/Gyroscope.m
src/__tests__/sensors.js
src/decorator.js
src/rnsensors.js
src/sensors.js

React native sensors does not have any method to know if the sensors are available. So I changed the way that it instantiate this package using a Promise which resolves in case of the sensors is available and rejects it if they are not.

Add the chance to know if the sensors are available

---

ios/Accelerometer.h
ios/Accelerometer.m
ios/Gyroscope.h
ios/Gyroscope.m

Fix invalid objc syntax & api misuse brought by #47

Fix method declarations and definitions

---

android/src/main/java/com/sensors/Accelerometer.java
android/src/main/java/com/sensors/Gyroscope.java
src/__tests__/__snapshots__/sensors.js.snap
src/__tests__/sensors.js
src/rnsensors.js
src/sensors.js

Relevant to #54.
P.S: I really believe you should integrate linters inside project... I've lost some time trying to rebase on StyleJS changes, but eventually dropped it and rewrote everything again.

Android: fix startUpdates API and update tests

---

ios/Accelerometer.m
ios/Gyroscope.m
ios/Magnetometer.m

```
"react": "16.3.1",
"react-native": "^0.55.4",
"react-native-sensors": "^3.0.0",
```

fix warnings with latest react version

---

android/build.gradle

This seems to be the standard way to deal with this in the react-native community.

Allow customizing compileSdkVersion

---

android/src/main/java/com/sensors/RNSensorsPackage.java

Fix method does not override or implement a method from a supertype

---

ios/Barometer.m

Barometer: NSNumber is already a NSNumber

---

ios/Accelerometer.m

chore: fixed spelling error in rejections

---

android/build.gradle

This has caused me quite some grief.
Instead of having users of this module override all versions in their build.gradle, forcing them to maintain these versions with every update they do, this change will simply take the latest version requested (from node_modules).
Now there are no more steps to take for android, and it just works after linking.
<details><summary>Click here to see the related warnings</summary>
<p>
```
> Task :app:checkDebugClasspath
WARNING: Conflict with dependency 'com.facebook.react:react-native' in project ':app'. Resolved versions for runtime classpath (0.20.1) and compile classpath (0.58.3) differ. This can lead to runtime crashes. To resolve this issue follow advice at https://developer.android.com/studio/build/gradle-tips#configure-project-wide-properties. …
```

fix(android): use latest available version of android

---

src/sensors.js

Fixed the callback of subscribe so it does stop the sensor

fix(callback): fixed the callback of subscribe so it does stop the sensor

---

android/build.gradle

Bump targetSdkVersion to 29

---

ios/Accelerometer.m
ios/Barometer.m
ios/Gyroscope.m
ios/Magnetometer.m
src/rnsensors.js
src/sensors.js

This adds supportedEvents to iOS #272 .
Tested on iPhone 5s and huawei honor 7 with android 6.0.

SupportedEvents

---

ios/Barometer.m

fix: make iOS compile by fixing logging error

---

.npmignore

These files don't need to be sent to npm. If you could merge this and create a new release, that would be awesome :)

Remove dev dependencies from the published npm package

---

android/build.gradle
android/src/main/java/com/sensors/RNSensor.java

As suggested by 
https://github.com/react-native-sensors/react-native-sensors/issues/253#issuecomment-511231664

Fix android x compatibility

---

ios/RNSensors.xcodeproj/project.pbxproj
ios/RNSensorsAccelerometer.h
ios/RNSensorsAccelerometer.m
ios/RNSensorsBarometer.h
ios/RNSensorsBarometer.m
ios/RNSensorsGyroscope.h
ios/RNSensorsGyroscope.m
ios/RNSensorsMagnetometer.h
ios/RNSensorsMagnetometer.m
ios/RNSensorsOrientation.h
ios/RNSensorsOrientation.m
ios/RNSensorsUtils.h
ios/RNSensorsUtils.m
package-lock.json
package.json
src/rnsensors.js

Closes #381
Per Release has been made, please test: https://github.com/react-native-sensors/react-native-sensors/releases/tag/v7.2.1-rc.1

Prefix native module files

---

.gitignore
.vscode/settings.json
android/src/main/java/com/sensors/RNSensor.java
android/src/main/java/com/sensors/RNSensorsPackage.java
index.d.ts
index.js
ios/RNSensorsGravity.h
ios/RNSensorsGravity.m
mock.js
src/rnsensors.js
src/sensors.js

I'm working to get the same for ios when user have gravity so linear acceleration can be calculated by
linearAcceleration = accelerometer - gravity

raw gravity added

---

src/sensors.js

fix: fix listener naming

---

ios/RNSensorsAccelerometer.m
ios/RNSensorsBarometer.m
ios/RNSensorsGravity.m
ios/RNSensorsGyroscope.m
ios/RNSensorsMagnetometer.m
ios/RNSensorsOrientation.m

fix: adjust ios sensor event name to match android
