ios/Accelerometer.m
ios/Gyroscope.m

Fixed the conversion from ms to s, related to https://github.com/react-native-sensors/react-native-sensors/issues/2
Checked on physical iPhone SE with example code that updates are now appearing at expected intervals.

Convert milliseconds to seconds for iOS.

---

index.js

Hi !
I had an issue when I tried your example.
The modules were exported by `default` and this is why I wasn't able to access to them.
It's my first pull request so I hope nothing is wrong.
Thanks for your work on this lib,
Julien

Fix export named module (as in examples)

---

package.json
src/decorator.js

This fixes issue with deprecated React.PropTypes in issue #31

Update to use prop-types instead of React.PropTypes

---

src/sensors.js

I tried installing react-native-sensors from scratch today, however it doesn't work due to a bug with rxjs. This is the suggested fix. I can confirm it fixes the problem.
See https://github.com/ReactiveX/rxjs/issues/3155

Fix import issue

---

src/rnsensors.js

Add error message for when linking has failed.
Previously: TypeError: undefined is not an object (evaluating 'api.setUpdateInterval')
After: Native modules for sensors not available. Did react-native link run successfully?

Add linking failure message

---

README.md
ios/Accelerometer.m
ios/Gyroscope.m
ios/Magnetometer.m

This ports changes suggested by @barbsicle to `react-native-sensors` latest version.
Original Pull Request: https://github.com/react-native-sensors/react-native-sensors/pull/132
Changes included do not touch any JS implementation. It's iOS/Objective-C only.

Do not crash iOS Simulator

---

docs/Usage.md

The example stated SensorTypes.Accelerometer, correct is SensorTypes.accelerometer

docs: Fixes a typo in example code

---

docs/API.md

magnetometer was incorrectly spelled magenetometer. 
The export in https://github.com/react-native-sensors/react-native-sensors/blob/master/src/sensors.js shows the correct way is magnetometer

docs: Fixes a typo in API documentation

---

ios/Barometer.m

There seems to be a logic error in the availability check for the barometer on iOS. Also, the barometer seems to always be available, so I removed the `CMPedometer` check as well.

Fix barometer on iOS.

---

index.d.ts

I have updated the following types
1. `setUpdateIntervalForType` -> The current implementation was not checking whether `type` was one of sensors in `SensorsTypes` or not, now it does.
2. `sensors` -> the old `RNSensor` didn't match the return of a real observable, so I replaced it with the real type.
3. The barometer sensor was returning the same data as the other sensors and that was wrong, so I created a custom type for that sensor.

[Typescript] Fix 'setsetUpdateIntervalForType' params & sensors type

---

ios/Accelerometer.h
ios/Accelerometer.m
ios/Barometer.h
ios/Barometer.m
ios/Gyroscope.h
ios/Gyroscope.m
ios/Magnetometer.h
ios/Magnetometer.m

I am not a iOS developer so feel free to tell me if i did anything wrong. 
This fixes #266 .
sendDeviceEventWithName is deprecated and probably has a memory leak.
What i did was changing it to use RCTEventEmitter sendEventWithName.

fix(iOS): Changed iOS to use RCTEventEmitter when sending messages to RN

---

android/src/main/java/com/sensors/Accelerometer.java
android/src/main/java/com/sensors/Barometer.java
android/src/main/java/com/sensors/Gyroscope.java
android/src/main/java/com/sensors/Magnetometer.java
android/src/main/java/com/sensors/Utils.java
index.d.ts
ios/Accelerometer.m
ios/Barometer.m
ios/Gyroscope.m
ios/Magnetometer.m
ios/RNSensors.xcodeproj/project.pbxproj
ios/Utils.h
ios/Utils.m
src/sensors.js

Currently the sensors timestamp in Android is the datetime current milliseconds and on iOS is the sensor timestamp that returns a timeinterval related to when the phone booted last time.
This pull request will generalize the sensors timestamps to Epoch milliseconds timestamps (calculated from the sensors original values).
Fixes #78
Additionally I did some spellcheck fixes, exposed the sensor types to be able to be used directly by the apps, and added timestamp to the Barometer sensor.

Consistent timestamp accross ios/android

---

index.d.ts

The field `timestamp` in the interface `SensorData` and `BarometerData` is typed wrong - the provided value is `number` but it's typed as a `string`.

fix(typings): timestamp to number

---

android/build.gradle

fix(minSdkVersion): Changed minSdkVersion from 23 to 17, since its the minimal for SystemClock.elapsedRealtimeNanos, as discussed in #322

Fix minSdkVersion to 17

---

RNSensors.podspec

According to https://github.com/facebook/react-native/issues/29633#issuecomment-694187116 - "React pod is in fact really only an umbrella dependency for pure JS applications to depend on, whereas the native APIs that these libraries rely on actually reside in the React-Core pod." and it will fail to build on Xcode12. This PR updates the dependency from `React` to `React-Core`.

fix: xcode 12 compatibility

---

android/src/main/java/com/sensors/RNSensor.java
android/src/main/java/com/sensors/RNSensorsPackage.java
docs/API.md
index.d.ts
index.js
ios/Orientation.h
ios/Orientation.m
ios/RNSensors.xcodeproj/project.pbxproj
src/rnsensors.js
src/sensors.js

Hello! I've added Orientation Sensor that returns rotation quaternion

Orientation sensor

---

index.d.ts

Hi! setLogLevelForType () was forgotten in 390b561 that updated the TS definitions, adding it with this PR.

Add missing setLogLevelForType TypeScript definition

---

docs/FAQ.md
mock.js

This PR adds Jest mocks to the library as discussed in #317.
If needed, even a sensor `subscribe()` observer can be tested as such:
```js
const { accelerometer } = jest.requireMock('react-native-sensors')
it('called our observer', () => {
const observer = jest.fn()
accelerometer.subscribe(observer)
expect(observer).toHaveBeenCalledTimes(1)
expect(observer).toHaveBeenCalledWith({ x: 0, y: 0, z: 0, timestamp: 0 })
})
```
You'll notice that I've set up all the values returned by the observer to `0` as that was the easiest thing to do right now. Would there be a need to test specific observer values, this approach would have to be modified.
I tested these changes with the app I'm working on right now by simply adding the following to my jest …

Add Jest mock implementation

---

ios/RNSensorsAccelerometer.m
ios/RNSensorsBarometer.m
ios/RNSensorsGyroscope.m
ios/RNSensorsMagnetometer.m
ios/RNSensorsOrientation.m

[v7.2.1-rc.1](https://github.com/react-native-sensors/react-native-sensors/releases/tag/v7.2.1-rc.1) fails to build because of some missed instances of renaming Utils to RNSensorsUtils.

Correct instances of missed renaming from Utils to RNSensorsUtils

---

ios/RNSensorsOrientation.m

Hello!
The orientation sensor did not work on the iOS device. I fixed it
When subscribing, we received only one response with the following value:
`{"pitch": 0, "qw": 0, "qx": 0, "qy": 0, "qz": 0, "roll": 0, "timestamp": 1640014079986, "yaw": 0}`

iOS orientation sensor fix

---

android/src/main/java/com/sensors/RNSensor.java

On Android, when running RN >= 0.65, we keep getting warnings:
```
'`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.'
```
Introduced in [this commit]('`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.')
This PR addresses this issue.

Fix RN warnings about EventListeners
